"""Additive TSV parser identity, sealed source evidence and legacy replay proof.

The legacy persisted snapshots were generated by frozen pre-change code, rather
than a second invocation of the current parser. All inputs are synthetic.
"""

from __future__ import annotations

import hashlib
import json
import sqlite3
from contextlib import closing
from dataclasses import asdict, replace
from pathlib import Path
from typing import Any

import pytest

from finance_core.intake import receipt_ocr_evidence as ocr
from finance_core.intake.receipt_ocr_proposal import (
    InvalidProposalCommandError,
    ProposalIdempotencyConflictError,
    ProposalSourceBindingConflictError,
    UnusableOcrEvidenceError,
)
from finance_core.intake.receipt_ocr_proposal import (
    ingest_receipt_ocr_evidence_as_total_expense_proposal as ingest,
)
from finance_core.openclaw_staging_bridge import ocr_boundary
from finance_core.parser_proposals import receipt_total_parser as parser
from tests import test_receipt_ocr_proposal_ingestion_v1 as legacy

FIXTURES = Path(__file__).parent / "fixtures" / "receipt_total_parser_v2"
VECTORS = json.loads((FIXTURES / "actual_synthetic_vectors.json").read_text())
LEGACY = json.loads((FIXTURES / "legacy_persisted_v1.json").read_text())
V2 = {
    "parser_version": parser.PARSER_VERSION_TSV_HIERARCHY,
    "parser_contract_version": parser.PARSER_CONTRACT_VERSION_TSV_HIERARCHY,
}


def parser_blocks(rows: list[dict[str, Any]]) -> tuple[parser.ParserOcrBlock, ...]:
    return tuple(
        parser.ParserOcrBlock(
            **{
                key: value
                for key, value in row.items()
                if key in parser.ParserOcrBlock.__dataclass_fields__
            }
        )
        for row in rows
    )


def counts(conn: sqlite3.Connection) -> tuple[int, ...]:
    return tuple(
        (
            conn.execute(f"SELECT COUNT(*) FROM {table}").fetchone()[0]
            if conn.execute(
                "SELECT 1 FROM sqlite_master WHERE type='table' AND name=?", (table,)
            ).fetchone()
            else 0
        )
        for table in (
            "parser_outputs",
            "parser_proposal_field_evidence",
            "receipt_ocr_proposal_links",
            "transactions",
            "receipts",
            "receipt_items",
            "receipt_item_allocation_fact_sets",
            "parser_proposal_confirmations",
            "calculation_snapshots",
            "receipt_proposal_conversions",
            "parser_proposal_conversion_audit",
        )
    )


def call(conn: sqlite3.Connection, suffix: str, **identity: Any):
    return ingest(
        conn,
        extraction_public_id=f"rocr_{suffix}",
        proposal_public_id=f"prop_{suffix}",
        link_public_id=f"ropl_{suffix}",
        **identity,
    )


@pytest.mark.parametrize("vector", VECTORS, ids=lambda vector: vector["format"])
def test_actual_synthetic_vector_preserves_v1_and_recovers_only_v2(vector):
    name = "synthetic_mixed_receipt." + ("jpg" if vector["format"] == "jpeg" else "png")
    source = FIXTURES.parent / "linux_receipt_ocr" / name
    assert hashlib.sha256(source.read_bytes()).hexdigest() == vector["source_sha256"]
    blocks = parser_blocks(vector["blocks"])
    assert len(blocks) == 32
    old = parser.parse_receipt_total(blocks, extraction_status="succeeded")
    assert old.amount.value is None and old.amount.block_sequence_indexes == ()
    for ordered in (blocks, tuple(reversed(blocks))):
        result = parser.parse_receipt_total(
            ordered, extraction_status="succeeded", parser_version="v2"
        )
        assert result.amount.value == "12.34" and result.currency.value == "HKD"
        assert result.amount.block_sequence_indexes == (22, 23, 24, 25)
        assert result.amount.excerpt == "fit TOTAL HKD 12.34"
    # The v2 grouping supplies no new AI role-proof groups.
    assert frozenset({22, 23, 24, 25}) not in parser.proven_layout_line_indexes(blocks)


@pytest.mark.parametrize("case", LEGACY["cases"], ids=lambda case: case["suffix"])
@pytest.mark.parametrize("explicit_version", [False, True], ids=["default", "explicit-v1"])
def test_frozen_old_code_persisted_records_replay_exactly(
    migrated_temp_db_connection, tmp_path, case, explicit_version
):
    conn = migrated_temp_db_connection
    suffix = case["suffix"]
    attachment = legacy._persist_attachment(conn, tmp_path, suffix=suffix)
    engine = legacy.FakeEngine(
        result=ocr.ReceiptOcrEngineResult(
            ocr.ReceiptOcrExtractionStatus.SUCCEEDED,
            tuple(ocr.ReceiptOcrBlock(**row) for row in case["blocks"]),
            "ok",
        )
    )
    engine._identity = ocr.ReceiptOcrEngineIdentity(**case["engine_identity"])
    extraction = ocr.extract_and_persist_receipt_ocr_evidence(
        conn, public_id=f"rocr_{suffix}", attachment_id=attachment, engine=engine
    )
    assert extraction.extraction_fingerprint == case["extraction_fingerprint"]
    assert extraction.normalized_result_hash == case["normalized_result_hash"]
    for table, rows in case["stored"].items():
        for row in rows:
            columns = ", ".join(row)
            parameters = ", ".join("?" for _ in row)
            conn.execute(
                f"INSERT INTO {table} ({columns}) VALUES ({parameters})", tuple(row.values())
            )
    conn.execute(
        "UPDATE raw_intake_records SET parser_output_id = ?, status = ?",
        (case["result"]["parser_output_id"], "parsed_pending_confirmation"),
    )
    conn.commit()
    before = counts(conn)
    database_before = _source_state(conn)
    stored_before = {
        table: [dict(row) for row in conn.execute(f"SELECT * FROM {table} ORDER BY id")]
        for table in case["stored"]
    }
    identity = {"parser_contract_version": case["result"]["parser_contract_version"]}
    if explicit_version:
        identity["parser_version"] = "v1"
    result = call(conn, suffix, **identity)
    assert result.idempotent is True
    for name in (
        "extraction_public_id",
        "proposal_public_id",
        "parser_output_id",
        "link_public_id",
        "proposal_input_hash",
        "proposal_result_hash",
        "parser_contract_version",
        "parse_status",
    ):
        assert getattr(result, name) == case["result"][name]
    assert list(result.ambiguity_flags) == case["result"]["ambiguity_flags"]
    assert counts(conn) == before and _source_state(conn) == database_before
    for table, rows in stored_before.items():
        assert [dict(row) for row in conn.execute(f"SELECT * FROM {table} ORDER BY id")] == rows
    with pytest.raises(ProposalIdempotencyConflictError):
        call(conn, suffix, **V2)
    assert counts(conn) == before
    # Existing raw pointer also forbids new IDs and another-version proposal.
    with pytest.raises(
        (
            ProposalSourceBindingConflictError,
            ProposalIdempotencyConflictError,
            UnusableOcrEvidenceError,
        )
    ):
        ingest(
            conn,
            extraction_public_id=f"rocr_{suffix}",
            proposal_public_id=f"prop_new_{suffix}",
            link_public_id=f"ropl_new_{suffix}",
            **V2,
        )
    assert counts(conn) == before and all(value == 0 for value in before[3:])


@pytest.mark.parametrize("vector", VECTORS, ids=lambda vector: vector["format"])
def test_v2_ingestion_verifies_original_hash_and_replays(
    migrated_temp_db_connection, tmp_path, vector
):
    conn = migrated_temp_db_connection
    suffix = "actual_" + vector["format"]
    legacy._prepare_extraction(
        conn,
        tmp_path,
        suffix=suffix,
        blocks=tuple(ocr.ReceiptOcrBlock(**row) for row in vector["blocks"]),
    )
    assert (
        conn.execute("SELECT normalized_result_hash FROM receipt_ocr_extractions").fetchone()[0]
        == vector["normalized_result_hash"]
    )
    first = call(conn, suffix, **V2)
    assert first.idempotent is False
    stored = conn.execute("SELECT * FROM parser_outputs").fetchone()
    payload = json.loads(stored["parsed_payload"])
    assert stored["parser_version"] == "v2"
    assert payload["amount"] == "12.34" and payload["currency"] == "HKD"
    assert payload["status"] == "parsed_pending_confirmation"
    assert payload["confirmation_required"] is True and payload["is_final"] is False
    assert payload["ocr_evidence"]["normalized_result_hash"] == vector["normalized_result_hash"]
    assert next(e for e in payload["field_evidence"] if e["field_name"] == "amount")[
        "block_sequence_indexes"
    ] == [22, 23, 24, 25]
    before = counts(conn)
    second = call(conn, suffix, **V2)
    assert second.idempotent is True and replace(second, idempotent=False) == first
    assert counts(conn) == before and before[0] == 1 and all(value == 0 for value in before[3:])
    with pytest.raises(ProposalIdempotencyConflictError):
        call(conn, suffix)
    assert counts(conn) == before


@pytest.mark.parametrize("field", ["page_index", "engine_block_index", "engine_paragraph_index"])
def test_v2_separates_reused_line_numbers(field):
    blocks = parser_blocks([asdict(b) for b in legacy._sgd_blocks()])
    total = tuple(replace(b, engine_line_index=0, **{field: 1}) for b in blocks[5:])
    other = blocks[:5]
    result = parser.parse_receipt_total(
        other + total, extraction_status="succeeded", parser_version="v2"
    )
    assert result.amount.value == "12.34" and result.amount.block_sequence_indexes == (5, 6, 7)


@pytest.mark.parametrize(
    "change",
    [
        {"engine_block_index": None},
        {"engine_paragraph_index": None},
        {"engine_line_index": None},
        {"engine_line_index": "0"},
        {"engine_line_index": True},
        {"page_index": -1},
        {"height": 0},
        {"height": None},
        {"top": 500},
        {"sequence_index": 0},
    ],
)
def test_v2_bad_group_rejects_whole_judgment(change):
    blocks = list(parser_blocks(VECTORS[0]["blocks"]))
    # A malformed non-total group must not be discarded to extract the good TOTAL.
    blocks[1] = replace(blocks[1], **change)
    with pytest.raises(ValueError):
        parser.parse_receipt_total(blocks, extraction_status="succeeded", parser_version="v2")


@pytest.mark.parametrize(
    "change",
    [
        {"engine_block_index": None},
        {"engine_paragraph_index": None},
        {"engine_line_index": None},
        {"height": 0},
        {"top": 500},
    ],
)
def test_v2_persisted_unusable_group_has_no_proposal_writes(
    migrated_temp_db_connection, tmp_path, change
):
    conn = migrated_temp_db_connection
    blocks = [ocr.ReceiptOcrBlock(**row) for row in VECTORS[0]["blocks"]]
    blocks[1] = replace(blocks[1], **change)
    legacy._prepare_extraction(conn, tmp_path, suffix="invalid", blocks=tuple(blocks))
    before = counts(conn)
    with pytest.raises(UnusableOcrEvidenceError):
        call(conn, "invalid", **V2)
    assert counts(conn) == before and all(value == 0 for value in before)


def test_v2_geometry_hash_drift_refused(migrated_temp_db_connection, tmp_path):
    conn = migrated_temp_db_connection
    legacy._prepare_extraction(conn, tmp_path, suffix="drift", blocks=legacy._sgd_blocks())
    # Deliberate database corruption in a synthetic test bypasses append-only protection.
    triggers = conn.execute(
        "SELECT name FROM sqlite_master WHERE type='trigger' AND tbl_name='receipt_ocr_blocks'"
    ).fetchall()
    for row in triggers:
        conn.execute(f'DROP TRIGGER "{row[0]}"')
    conn.execute("UPDATE receipt_ocr_blocks SET coordinate_height=11 WHERE sequence_index=0")
    conn.commit()
    with pytest.raises(UnusableOcrEvidenceError, match="normalized hash"):
        call(conn, "drift", **V2)
    assert all(value == 0 for value in counts(conn))


@pytest.mark.parametrize(
    "version,contract",
    [
        ("v3", parser.PARSER_CONTRACT_VERSION_DEFAULT),
        ("v2", parser.PARSER_CONTRACT_VERSION_DEFAULT),
        ("v2", "custom.legacy-token"),
    ],
)
def test_unknown_or_inconsistent_parser_identity_refused(
    migrated_temp_db_connection, version, contract
):
    with pytest.raises(InvalidProposalCommandError):
        call(
            migrated_temp_db_connection,
            "no_source",
            parser_version=version,
            parser_contract_version=contract,
        )
    assert all(value == 0 for value in counts(migrated_temp_db_connection))


@pytest.mark.parametrize(
    "status",
    [s for s in ocr.ReceiptOcrExtractionStatus if s != ocr.ReceiptOcrExtractionStatus.SUCCEEDED],
)
def test_v2_failure_status_compatibility(status):
    assert parser.parse_receipt_total(
        (), extraction_status=status.value, parser_version="v2"
    ) == parser.parse_receipt_total((), extraction_status=status.value)


@pytest.mark.parametrize(
    "marker,value",
    [("HKD", "-5.00"), ("HKD", "12.345"), ("$", "12.34"), ("RM", "12.34"), ("XYZ", "12.34")],
)
def test_v2_keeps_financial_refusals(marker, value):
    blocks = legacy._sgd_blocks(total_marker=marker, total_value=value)
    view = parser_blocks([asdict(b) for b in blocks])
    old = parser.parse_receipt_total(view, extraction_status="succeeded")
    new = parser.parse_receipt_total(view, extraction_status="succeeded", parser_version="v2")
    assert new == old and new.amount.value is None


def test_v2_conflicting_legitimate_totals_stay_ambiguous():
    first = parser_blocks([asdict(b) for b in legacy._sgd_blocks()])
    second = tuple(
        replace(
            b,
            sequence_index=b.sequence_index + 3,
            engine_paragraph_index=1,
            text="99.99" if b.sequence_index == 7 else b.text,
        )
        for b in first[5:]
    )
    result = parser.parse_receipt_total(
        first + second, extraction_status="succeeded", parser_version="v2"
    )
    assert result.amount.value is None and parser.FLAG_CONFLICTING_TOTALS in result.ambiguity_flags


def test_trusted_same_engine_capability_selects_v2_and_name_spoof_does_not(monkeypatch, tmp_path):
    built = legacy.FakeEngine(
        result=ocr.ReceiptOcrEngineResult(ocr.ReceiptOcrExtractionStatus.NO_TEXT, (), "no_text")
    )
    built._identity = replace(built.identity, name="tesseract_tsv")
    assert ocr_boundary.receipt_parser_identity(built) == (
        "v1",
        parser.PARSER_CONTRACT_VERSION_DEFAULT,
    )
    monkeypatch.setattr(ocr_boundary.sys, "platform", "linux")
    seen = []

    def factory(*args, **kwargs):
        seen.append(kwargs["pinned_resources"])
        return built

    monkeypatch.setattr(ocr, "TesseractTsvOcrEngine", factory)
    payload = {
        "schema_version": "v2",
        "engine": "tesseract_tsv",
        "helper_path": str(tmp_path / "binary"),
        "expected_version": "1.0",
        "binary_sha256": built.identity.binary_sha256,
        "tessdata_directory": str(tmp_path / "models"),
        "language_resources": [
            {"language": lang, "size_bytes": 1, "sha256": "a" * 64} for lang in ("eng", "chi_sim")
        ],
    }
    monkeypatch.setattr(ocr_boundary, "_load_workspace_engine_config", lambda workspace: payload)
    engine = ocr_boundary.resolve_workspace_ocr_engine(tmp_path)
    assert len(seen) == 1 and engine.identity is built.identity
    # Config may change after resolution; identity selection uses this exact engine.
    monkeypatch.setattr(
        ocr_boundary,
        "_load_workspace_engine_config",
        lambda workspace: pytest.fail("independent configuration reread"),
    )
    assert ocr_boundary.receipt_parser_identity(engine) == (
        "v2",
        parser.PARSER_CONTRACT_VERSION_TSV_HIERARCHY,
    )
    assert engine.extract(None, limits=ocr.ReceiptOcrLimits(), deadline=1) is built.result
    monkeypatch.setattr(ocr_boundary, "engine_factory", lambda workspace: built)
    assert ocr_boundary.build_ocr_engine(tmp_path) is built
    assert ocr_boundary.receipt_parser_identity(ocr_boundary.build_ocr_engine(tmp_path))[0] == "v1"


def test_v2_partial_total_token_in_another_hierarchy_stays_incomplete():
    blocks = list(parser_blocks(VECTORS[0]["blocks"]))
    blocks[25] = replace(blocks[25], engine_paragraph_index=99)
    result = parser.parse_receipt_total(blocks, extraction_status="succeeded", parser_version="v2")
    assert result.amount.value is None and result.currency.value is None
    assert parser.FLAG_TOTAL_NOT_FOUND in result.ambiguity_flags


def test_v2_replay_parser_identity_corruption_refused(migrated_temp_db_connection, tmp_path):
    from finance_core.intake.receipt_ocr_proposal import ProposalPersistenceConflictError

    conn = migrated_temp_db_connection
    legacy._prepare_extraction(conn, tmp_path, suffix="identity", blocks=legacy._sgd_blocks())
    call(conn, "identity", **V2)
    before = counts(conn)
    triggers = conn.execute(
        "SELECT name FROM sqlite_master WHERE type='trigger' AND tbl_name='parser_outputs'"
    ).fetchall()
    for row in triggers:
        conn.execute(f'DROP TRIGGER "{row[0]}"')
    conn.execute("UPDATE parser_outputs SET parser_name='another-parser'")
    conn.commit()
    with pytest.raises(ProposalPersistenceConflictError):
        call(conn, "identity", **V2)
    assert counts(conn) == before


@pytest.mark.parametrize(
    "trusted_linux", [False, True], ids=["legacy-name-only", "trusted-capability"]
)
def test_bridge_selected_identity_and_existing_proposal_replay(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch, trusted_linux: bool
) -> None:
    import openclaw_staging_bridge_support_v1 as support

    from finance_core.openclaw_staging_bridge import errors
    from tests.test_openclaw_staging_bridge_propose_review_v1 import capture_receipt

    workspace = support.create_bridge_workspace(tmp_path)
    fake = support.FakeOcrEngine(
        blocks=tuple(ocr.ReceiptOcrBlock(**row) for row in VECTORS[0]["blocks"])
    )
    fake._identity = replace(fake.identity, name="tesseract_tsv")
    selected = ocr_boundary._PinnedLinuxReceiptEngine(fake) if trusted_linux else fake
    monkeypatch.setattr(ocr_boundary, "engine_factory", lambda workspace: selected)
    captured = capture_receipt(workspace, "synthetic-parser-version")
    arguments = {
        "workspace_path": str(workspace.workspace_path),
        "intake_public_id": captured["intake_public_id"],
    }
    key = support.canonical_propose_key(captured["intake_public_id"])
    # A request cannot opt into a parser version.
    rejected = support.run_cli(
        support.make_request("propose", {**arguments, "parser_version": "v2"}, idempotency_key=key)
    )
    assert rejected.exit_code != errors.EXIT_OK and fake.calls == 0
    first = support.run_cli(support.make_request("propose", arguments, idempotency_key=key))
    assert first.exit_code == errors.EXIT_OK, first.response
    assert fake.calls == 1
    with support.open_database(workspace) as conn:
        row = conn.execute("SELECT parser_version, parsed_payload FROM parser_outputs").fetchone()
        assert row["parser_version"] == ("v2" if trusted_linux else "v1")
        payload = json.loads(row["parsed_payload"])
        assert payload["amount"] == ("12.34" if trusted_linux else None)
        assert payload["confirmation_required"] is True and payload["is_final"] is False
        before = counts(conn)
    # Returning an existing v1/v2 proposal precedes resolution; a new trusted
    # Linux configuration cannot reparse or replace its raw-intake pointer.
    monkeypatch.setattr(
        ocr_boundary,
        "engine_factory",
        lambda workspace: pytest.fail("replay must not resolve another engine"),
    )
    second = support.run_cli(support.make_request("propose", arguments, idempotency_key=key))
    assert second.exit_code == errors.EXIT_OK and second.response["idempotent_replay"] is True
    assert (
        second.response["result"]["proposal_public_id"]
        == first.response["result"]["proposal_public_id"]
    )
    with support.open_database(workspace) as conn:
        assert counts(conn) == before and before[0] == 1 and all(value == 0 for value in before[3:])
    assert fake.calls == 1


def _source_state(conn: sqlite3.Connection) -> tuple[str, ...]:
    """Include B's committed source rows, pointers and every A-owned table."""
    return tuple(conn.iterdump())


@pytest.mark.parametrize("race", ["public-id", "second-source", "replay-second-source"])
def test_v2_locked_source_races_refuse_without_any_a_writes(
    migrated_temp_db_connection, migrated_temp_db_path, tmp_path, monkeypatch, race
):
    from finance_core.intake import receipt_ocr_proposal as proposal
    from tests.conftest import connect_temp_db

    conn = migrated_temp_db_connection
    suffix = "locked_source"
    legacy._prepare_extraction(conn, tmp_path, suffix=suffix, blocks=legacy._sgd_blocks())
    if race == "replay-second-source":
        first = call(conn, suffix, **V2)
        before_replay = _source_state(conn)
        replay = call(conn, suffix, **V2)
        assert replay.idempotent and replace(replay, idempotent=False) == first
        assert _source_state(conn) == before_replay
    schema = tuple(conn.execute("SELECT type, name, sql FROM sqlite_master ORDER BY name"))
    original_persist = proposal._persist
    baseline = None
    baseline_counts = None

    def commit_b_then_persist(connection, **kwargs):
        nonlocal baseline, baseline_counts
        with closing(connect_temp_db(migrated_temp_db_path)) as other:
            assert other.execute("PRAGMA foreign_keys").fetchone()[0] == 1
            if race == "public-id":
                other.execute(
                    "UPDATE raw_intake_records SET public_id = 'raw_committed_change' "
                    "WHERE public_id = ?",
                    (f"raw_ocr_{suffix}",),
                )
                other.commit()
            else:
                if race == "replay-second-source":
                    # The existing lineage trigger legitimately freezes this identity.
                    with pytest.raises(sqlite3.IntegrityError):
                        other.execute(
                            "UPDATE raw_intake_records SET public_id = 'raw_blocked_change' "
                            "WHERE public_id = ?",
                            (f"raw_ocr_{suffix}",),
                        )
                    other.rollback()
                second_raw = legacy._insert_raw_intake(other, "locked_second")
                source = other.execute("SELECT * FROM telegram_attachment_source").fetchone()
                other.execute(
                    "INSERT INTO telegram_attachment_source (public_id, attachment_id, "
                    "raw_intake_record_id, original_attachment_path, observed_file_size, "
                    "content_hash, source_evidence_payload) VALUES (?, ?, ?, ?, ?, ?, ?)",
                    (
                        "tgae_locked_second",
                        source["attachment_id"],
                        second_raw,
                        source["original_attachment_path"],
                        source["observed_file_size"],
                        source["content_hash"],
                        source["source_evidence_payload"],
                    ),
                )
                other.commit()
            assert other.execute("PRAGMA foreign_key_check").fetchall() == []
            # Snapshot after B commits, before A acquires its lock or writes.
            baseline = _source_state(other)
            baseline_counts = counts(other)
        return original_persist(connection, **kwargs)

    monkeypatch.setattr(proposal, "_persist", commit_b_then_persist)
    with pytest.raises(ProposalSourceBindingConflictError):
        call(conn, suffix, **V2)
    assert baseline is not None and _source_state(conn) == baseline
    assert counts(conn) == baseline_counts
    assert tuple(conn.execute("SELECT type, name, sql FROM sqlite_master ORDER BY name")) == schema
    assert not conn.in_transaction
    assert all(value == 0 for value in counts(conn)[3:])
    if race == "public-id":
        raw = conn.execute("SELECT public_id, parser_output_id FROM raw_intake_records").fetchone()
        assert tuple(raw) == ("raw_committed_change", None)
    else:
        assert conn.execute("SELECT COUNT(*) FROM telegram_attachment_source").fetchone()[0] == 2
        assert (
            conn.execute(
                "SELECT parser_output_id FROM raw_intake_records "
                "WHERE public_id = 'raw_ocr_locked_second'"
            ).fetchone()[0]
            is None
        )
    if race != "replay-second-source":
        assert counts(conn)[:3] == (0, 0, 0)


@pytest.mark.parametrize(
    "field",
    ["attachment_id", "attachment_public_id", "raw_intake_record_id", "raw_intake_public_id"],
)
def test_v2_locked_resolver_compares_every_prefetched_binding_field(
    migrated_temp_db_connection, tmp_path, monkeypatch, field
):
    from finance_core.intake import receipt_ocr_proposal as proposal

    conn = migrated_temp_db_connection
    suffix = "binding_field"
    legacy._prepare_extraction(conn, tmp_path, suffix=suffix, blocks=legacy._sgd_blocks())
    before = _source_state(conn)
    resolver = proposal._resolve_source_binding
    calls = 0

    def changed_binding(connection, extraction):
        nonlocal calls
        calls += 1
        binding = resolver(connection, extraction)
        if calls == 2:
            assert connection.in_transaction
            value = getattr(binding, field)
            return replace(
                binding, **{field: value + 1 if isinstance(value, int) else value + "_drift"}
            )
        assert not connection.in_transaction
        return binding

    def no_link_lookup(*args, **kwargs):
        pytest.fail("source guard must precede link lookup")

    monkeypatch.setattr(proposal, "_resolve_source_binding", changed_binding)
    monkeypatch.setattr(proposal, "_lookup_link_by_public_id", no_link_lookup)
    with pytest.raises(ProposalSourceBindingConflictError, match="changed before persistence"):
        call(conn, suffix, **V2)
    assert calls == 2 and not conn.in_transaction and _source_state(conn) == before


@pytest.mark.parametrize("failure", ["missing", "dual source", "hash mismatch"])
def test_v2_locked_resolver_conflict_rolls_back_before_link_lookup(
    migrated_temp_db_connection, tmp_path, monkeypatch, failure
):
    from finance_core.intake import receipt_ocr_proposal as proposal

    conn = migrated_temp_db_connection
    suffix = "locked_conflict"
    legacy._prepare_extraction(conn, tmp_path, suffix=suffix, blocks=legacy._sgd_blocks())
    before = _source_state(conn)
    resolver = proposal._resolve_source_binding

    def conflicted_binding(connection, extraction):
        if connection.in_transaction:
            raise ProposalSourceBindingConflictError(failure)
        return resolver(connection, extraction)

    def no_link_lookup(*args, **kwargs):
        pytest.fail("source conflict must precede link lookup")

    monkeypatch.setattr(proposal, "_resolve_source_binding", conflicted_binding)
    monkeypatch.setattr(proposal, "_lookup_link_by_public_id", no_link_lookup)
    with pytest.raises(ProposalSourceBindingConflictError, match=failure):
        call(conn, suffix, **V2)
    assert not conn.in_transaction and _source_state(conn) == before


_AGGREGATE_MUTATIONS = (
    "source_public_id",
    "attachment_null",
    "attachment_other",
    "parent_parser_output_id",
    "statement_batch_id",
    "ai_provider",
    "ai_model",
    "prompt_version",
    "raw_text",
    "normalized_payload",
    "parsed_payload",
    "confidence_score",
    "evidence_missing",
    "evidence_extra",
    "evidence_field_name",
    "evidence_proposed_value",
    "evidence_confidence_score",
    "evidence_source_type",
    "evidence_reference",
    "evidence_notes",
    "evidence_parser_output_id",
    "pointer_child",
)


def _prepare_aggregate(conn, tmp_path):
    suffix = "aggregate"
    legacy._prepare_extraction(conn, tmp_path, suffix=suffix, blocks=legacy._sgd_blocks())
    other_attachment = legacy._persist_attachment(conn, tmp_path, suffix="aggregate_other")
    other_id = conn.execute(
        "INSERT INTO parser_outputs (public_id, source_type, parse_status) "
        "VALUES ('prop_aggregate_other', 'telegram_image', 'parsed_pending_confirmation')"
    ).lastrowid
    conn.commit()
    return suffix, other_attachment, other_id


def _mutate_pending_aggregate(conn, mutation, proposal_id, other_attachment, other_id):
    """Legal single-surface changes; retain every original trigger and FK."""
    if mutation == "pointer_child":
        child_id = conn.execute(
            "INSERT INTO parser_outputs (public_id, source_type, source_public_id, "
            "parent_parser_output_id, parse_status) VALUES "
            "('prop_aggregate_child', 'telegram_image', 'raw_ocr_aggregate', ?, "
            "'parsed_pending_confirmation')",
            (proposal_id,),
        ).lastrowid
        conn.execute(
            "UPDATE raw_intake_records SET parser_output_id = ? WHERE public_id = ?",
            (child_id, "raw_ocr_aggregate"),
        )
        assert (
            conn.execute(
                "SELECT parse_status FROM parser_outputs WHERE id = ?", (proposal_id,)
            ).fetchone()[0]
            == "parsed_pending_confirmation"
        )
    elif mutation == "statement_batch_id":
        batch_id = conn.execute(
            "INSERT INTO statement_batches (public_id, statement_source) "
            "VALUES ('batch_aggregate_other', 'synthetic')"
        ).lastrowid
        conn.execute(
            "UPDATE parser_outputs SET statement_batch_id = ? WHERE id = ?",
            (batch_id, proposal_id),
        )
    elif mutation == "evidence_missing":
        conn.execute(
            "DELETE FROM parser_proposal_field_evidence WHERE id = "
            "(SELECT MIN(id) FROM parser_proposal_field_evidence WHERE parser_output_id = ?)",
            (proposal_id,),
        )
    elif mutation == "evidence_extra":
        # A duplicate material row must be counted, not collapsed into a set.
        conn.execute(
            "INSERT INTO parser_proposal_field_evidence (parser_output_id, field_name, "
            "proposed_value, confidence_score, evidence_source_type, evidence_reference, notes) "
            "SELECT parser_output_id, field_name, proposed_value, confidence_score, "
            "evidence_source_type, evidence_reference, notes "
            "FROM parser_proposal_field_evidence WHERE parser_output_id = ? LIMIT 1",
            (proposal_id,),
        )
    elif mutation.startswith("evidence_"):
        field = (
            mutation
            if mutation in {"evidence_source_type", "evidence_reference"}
            else mutation.removeprefix("evidence_")
        )
        value = {
            "parser_output_id": other_id,
            "field_name": "description",
            "proposed_value": "changed",
            "confidence_score": 0.01,
            "evidence_source_type": "user_message",
            "evidence_reference": '{"extraction_public_id":"rocr_other"}',
            "notes": "changed excerpt",
        }[field]
        conn.execute(
            f"UPDATE parser_proposal_field_evidence SET {field} = ? WHERE id = "
            "(SELECT MIN(id) FROM parser_proposal_field_evidence WHERE parser_output_id = ?)",
            (value, proposal_id),
        )
    else:
        field, value = {
            "source_public_id": ("source_public_id", "raw_ocr_aggregate_other"),
            "attachment_null": ("attachment_id", None),
            "attachment_other": ("attachment_id", other_attachment),
            "parent_parser_output_id": ("parent_parser_output_id", other_id),
            "ai_provider": ("ai_provider", "synthetic-provider"),
            "ai_model": ("ai_model", "synthetic-model"),
            "prompt_version": ("prompt_version", "synthetic-prompt"),
            "raw_text": ("raw_text", "synthetic-text"),
            "normalized_payload": ("normalized_payload", "{}"),
            "parsed_payload": ("parsed_payload", "{}"),
            "confidence_score": ("confidence_score", 0.01),
        }[mutation]
        conn.execute(f"UPDATE parser_outputs SET {field} = ? WHERE id = ?", (value, proposal_id))
    assert conn.execute("PRAGMA foreign_keys").fetchone()[0] == 1
    assert conn.execute("PRAGMA foreign_key_check").fetchall() == []


@pytest.mark.parametrize("mutation", _AGGREGATE_MUTATIONS)
@pytest.mark.parametrize("prelock_commit", [False, True], ids=["committed", "a-preload-b-commit"])
def test_v2_pending_aggregate_refuses_legal_drift_without_a_writes(
    migrated_temp_db_connection,
    migrated_temp_db_path,
    tmp_path,
    monkeypatch,
    mutation,
    prelock_commit,
):
    from finance_core.intake import receipt_ocr_proposal as proposal
    from tests.conftest import connect_temp_db

    conn = migrated_temp_db_connection
    suffix, other_attachment, other_id = _prepare_aggregate(conn, tmp_path)
    first = call(conn, suffix, **V2)
    schema = tuple(conn.execute("SELECT type, name, sql FROM sqlite_master ORDER BY name"))
    baseline = None
    baseline_counts = None

    def mutate_and_snapshot(connection):
        nonlocal baseline, baseline_counts
        _mutate_pending_aggregate(
            connection, mutation, first.parser_output_id, other_attachment, other_id
        )
        connection.commit()
        baseline, baseline_counts = _source_state(connection), counts(connection)

    if prelock_commit:
        original = proposal._persist

        def b_commit_then_a_lock(connection, **kwargs):
            assert not connection.in_transaction
            with closing(connect_temp_db(migrated_temp_db_path)) as other:
                mutate_and_snapshot(other)
            return original(connection, **kwargs)

        monkeypatch.setattr(proposal, "_persist", b_commit_then_a_lock)
    else:
        mutate_and_snapshot(conn)
    with pytest.raises(proposal.ProposalPersistenceConflictError):
        call(conn, suffix, **V2)
    assert baseline is not None and _source_state(conn) == baseline
    assert counts(conn) == baseline_counts and all(value == 0 for value in counts(conn)[3:])
    assert tuple(conn.execute("SELECT type, name, sql FROM sqlite_master ORDER BY name")) == schema
    assert not conn.in_transaction


@pytest.mark.parametrize("mutation", _AGGREGATE_MUTATIONS)
def test_v2_initial_after_write_aggregate_drift_rolls_back_every_write(
    migrated_temp_db_connection, tmp_path, monkeypatch, mutation
):
    from finance_core.intake import receipt_ocr_proposal as proposal

    conn = migrated_temp_db_connection
    suffix, other_attachment, other_id = _prepare_aggregate(conn, tmp_path)
    baseline, baseline_counts = _source_state(conn), counts(conn)

    def drift(stage):
        if stage == "before_persisted_verification":
            proposal_id = conn.execute(
                "SELECT id FROM parser_outputs WHERE public_id = 'prop_aggregate'"
            ).fetchone()[0]
            _mutate_pending_aggregate(conn, mutation, proposal_id, other_attachment, other_id)

    monkeypatch.setattr(proposal, "_failure_injection_hook", drift)
    with pytest.raises(proposal.ProposalPersistenceConflictError):
        call(conn, suffix, **V2)
    assert _source_state(conn) == baseline and counts(conn) == baseline_counts
    assert not conn.in_transaction and all(value == 0 for value in counts(conn)[3:])


@pytest.mark.parametrize("pointer", [None, "unrelated"])
def test_v2_original_pointer_trigger_refuses_detach_or_unrelated(
    migrated_temp_db_connection, tmp_path, pointer
):
    conn = migrated_temp_db_connection
    suffix, _attachment, other_id = _prepare_aggregate(conn, tmp_path)
    call(conn, suffix, **V2)
    baseline = _source_state(conn)
    with pytest.raises(sqlite3.IntegrityError, match="cannot be detached or retargeted"):
        conn.execute(
            "UPDATE raw_intake_records SET parser_output_id = ? WHERE public_id = ?",
            (None if pointer is None else other_id, "raw_ocr_aggregate"),
        )
    conn.rollback()
    assert _source_state(conn) == baseline
    assert call(conn, suffix, **V2).idempotent


@pytest.mark.parametrize(
    "link_field",
    [
        "public_id",
        "extraction_id",
        "parser_output_id",
        "parser_contract_version",
        "link_role",
        "proposal_input_hash",
        "proposal_result_hash",
    ],
)
def test_v2_complete_initial_link_identity_checked_without_trigger_removal(
    migrated_temp_db_connection, tmp_path, monkeypatch, link_field
):
    from finance_core.intake import receipt_ocr_proposal as proposal

    conn = migrated_temp_db_connection
    suffix, _attachment, other_id = _prepare_aggregate(conn, tmp_path)
    legacy._prepare_extraction(
        conn,
        tmp_path,
        suffix="link_other",
        blocks=legacy._sgd_blocks(),
        content=legacy.JPEG + b"-link-other",
    )
    other_extraction = conn.execute(
        "SELECT id FROM receipt_ocr_extractions WHERE public_id = 'rocr_link_other'"
    ).fetchone()[0]
    baseline = _source_state(conn)
    original = proposal._insert_link

    def insert_wrong_link(connection, **kwargs):
        command = kwargs["command"]
        if link_field in ("public_id", "parser_contract_version"):
            key = "link_public_id" if link_field == "public_id" else link_field
            kwargs["command"] = replace(command, **{key: "ropl_other_identity"})
        elif link_field == "extraction_id":
            kwargs["extraction"] = replace(kwargs["extraction"], id=other_extraction)
        elif link_field == "parser_output_id":
            kwargs["parser_output_id"] = other_id
        elif link_field == "link_role":
            # Use the existing schema-legal reserved correction role directly.
            connection.execute(
                "INSERT INTO receipt_ocr_proposal_links (public_id, extraction_id, "
                "parser_output_id, proposal_input_hash, proposal_result_hash, "
                "parser_contract_version, link_role) VALUES (?, ?, ?, ?, ?, ?, ?)",
                (
                    command.link_public_id,
                    kwargs["extraction"].id,
                    kwargs["parser_output_id"],
                    kwargs["proposal_input_hash"],
                    kwargs["proposal_result_hash"],
                    command.parser_contract_version,
                    "superseding_correction",
                ),
            )
            return
        else:
            kwargs[link_field] = "a" * 64
        original(connection, **kwargs)

    monkeypatch.setattr(proposal, "_insert_link", insert_wrong_link)
    with pytest.raises(proposal.ProposalPersistenceConflictError):
        call(conn, suffix, **V2)
    assert _source_state(conn) == baseline and not conn.in_transaction


def test_v2_evidence_nonmaterial_id_time_order_changes_replay_exactly(
    migrated_temp_db_connection, tmp_path
):
    conn = migrated_temp_db_connection
    suffix, _attachment, _other_id = _prepare_aggregate(conn, tmp_path)
    first = call(conn, suffix, **V2)
    conn.execute(
        "UPDATE parser_proposal_field_evidence SET id = id + 100, created_at = '2000-01-01' "
        "WHERE parser_output_id = ?",
        (first.parser_output_id,),
    )
    conn.commit()
    baseline = _source_state(conn)
    replay = call(conn, suffix, **V2)
    assert replace(replay, idempotent=False) == first and replay.idempotent
    assert _source_state(conn) == baseline


@pytest.mark.parametrize("status", ["edited_pending_confirmation", "superseded"])
def test_v2_existing_nonoriginal_pending_status_refusal_is_preserved(
    migrated_temp_db_connection, tmp_path, status
):
    from finance_core.intake.receipt_ocr_proposal import ProposalPersistenceConflictError

    conn = migrated_temp_db_connection
    suffix, _attachment, _other_id = _prepare_aggregate(conn, tmp_path)
    first = call(conn, suffix, **V2)
    conn.execute(
        "UPDATE parser_outputs SET parse_status = ? WHERE id = ?", (status, first.parser_output_id)
    )
    conn.commit()
    baseline = _source_state(conn)
    with pytest.raises(ProposalPersistenceConflictError):
        call(conn, suffix, **V2)
    assert _source_state(conn) == baseline and not conn.in_transaction


def test_v2_guarded_human_revision_retains_parent_replay_refusal(
    migrated_temp_db_connection, tmp_path
):
    from finance_core.intake.receipt_ocr_proposal import ProposalPersistenceConflictError
    from finance_core.parser_proposals.content_hash import compute_effective_proposal_content_hash
    from finance_core.parser_proposals.receipt_supersession import supersede_receipt_total_proposal

    conn = migrated_temp_db_connection
    suffix, _attachment, _other_id = _prepare_aggregate(conn, tmp_path)
    first = call(conn, suffix, **V2)
    parent = dict(
        conn.execute(
            "SELECT * FROM parser_outputs WHERE id = ?", (first.parser_output_id,)
        ).fetchone()
    )
    supersede_receipt_total_proposal(
        conn,
        first.parser_output_id,
        actor="synthetic-human",
        expected_content_hash=compute_effective_proposal_content_hash(conn, parent),
        field_updates={"amount": "13.00", "currency": "SGD"},
        correction_public_id="rcor_aggregate_human",
    )
    assert (
        conn.execute(
            "SELECT parse_status FROM parser_outputs WHERE id = ?", (first.parser_output_id,)
        ).fetchone()[0]
        == "superseded"
    )
    pointer = conn.execute(
        "SELECT parser_output_id FROM raw_intake_records WHERE public_id = 'raw_ocr_aggregate'"
    ).fetchone()[0]
    assert pointer != first.parser_output_id
    assert (
        conn.execute(
            "SELECT parent_parser_output_id FROM parser_outputs WHERE id = ?", (pointer,)
        ).fetchone()[0]
        == first.parser_output_id
    )
    baseline = _source_state(conn)
    with pytest.raises(ProposalPersistenceConflictError):
        call(conn, suffix, **V2)
    assert _source_state(conn) == baseline and all(value == 0 for value in counts(conn)[3:])


@pytest.mark.parametrize("operation", ["update", "delete"])
def test_v2_original_ocr_link_append_only_triggers_retained(
    migrated_temp_db_connection, tmp_path, operation
):
    conn = migrated_temp_db_connection
    suffix, _attachment, _other_id = _prepare_aggregate(conn, tmp_path)
    call(conn, suffix, **V2)
    baseline = _source_state(conn)
    with pytest.raises(sqlite3.IntegrityError, match="append-only"):
        if operation == "update":
            conn.execute(
                "UPDATE receipt_ocr_proposal_links SET proposal_result_hash = ?", ("a" * 64,)
            )
        else:
            conn.execute("DELETE FROM receipt_ocr_proposal_links")
    conn.rollback()
    assert _source_state(conn) == baseline and call(conn, suffix, **V2).idempotent
