"""Intake module — raw input, Telegram adaptation, and attachment boundaries.

Public API:
  acquire_and_persist_telegram_attachment — bounded network/storage/evidence service
  TelegramBotApiTransport                — credential-safe concrete HTTPS transport
  persist_attachment_evidence            — persist filesystem-derived evidence
  get_attachment_evidence                — read-only evidence lookup
  extract_and_persist_receipt_ocr_evidence — bounded append-only OCR evidence
  MacOSVisionOcrEngine                   — bounded macOS Apple Vision OCR engine (B2)
"""

from finance_core.intake.attachment_evidence import (
    AttachmentEvidenceConflictError,
    AttachmentEvidenceError,
    AttachmentEvidencePersistenceError,
    AttachmentExpectedHashMismatchError,
    AttachmentExpectedSizeMismatchError,
    AttachmentFileChangedDuringHashError,
    AttachmentFileNotFoundError,
    AttachmentFileUnreadableError,
    AttachmentRawIntakeConflictError,
    InvalidAttachmentIdentityError,
    get_attachment_evidence,
    persist_attachment_evidence,
)
from finance_core.intake.macos_vision_receipt_ocr import (
    HELPER_NAME as MACOS_VISION_HELPER_NAME,
)
from finance_core.intake.macos_vision_receipt_ocr import (
    HELPER_PROTOCOL_VERSION as MACOS_VISION_HELPER_PROTOCOL_VERSION,
)
from finance_core.intake.macos_vision_receipt_ocr import (
    MAX_LANGUAGE_COUNT as MACOS_VISION_MAX_LANGUAGE_COUNT,
)
from finance_core.intake.macos_vision_receipt_ocr import (
    RECOGNITION_LEVEL as MACOS_VISION_RECOGNITION_LEVEL,
)
from finance_core.intake.macos_vision_receipt_ocr import (
    USES_LANGUAGE_CORRECTION as MACOS_VISION_USES_LANGUAGE_CORRECTION,
)
from finance_core.intake.macos_vision_receipt_ocr import (
    VISION_REQUEST_REVISION as MACOS_VISION_REQUEST_REVISION,
)
from finance_core.intake.macos_vision_receipt_ocr import (
    MacOSVisionOcrEngine,
    OcrProcessCleanupError,
    convert_vision_bounding_box,
    convert_vision_observations,
    scale_vision_confidence,
)
from finance_core.intake.receipt_ocr_evidence import (
    InvalidOcrConfigurationError,
    MalformedOcrOutputError,
    OcrAttachmentIntegrityConflictError,
    OcrAttachmentNotFoundError,
    OcrCallerOwnedTransactionError,
    OcrDeadlineExceededError,
    OcrEngineLaunchError,
    OcrIdempotencyConflictError,
    OcrPersistenceConflictError,
    OcrResourceLimitExceededError,
    OcrStagingDatabaseRejectedError,
    OcrUnexpectedPersistenceError,
    OcrUnsupportedPlatformError,
    ReceiptOcrBlock,
    ReceiptOcrEngine,
    ReceiptOcrEngineIdentity,
    ReceiptOcrEngineResult,
    ReceiptOcrError,
    ReceiptOcrExtractionResult,
    ReceiptOcrExtractionStatus,
    ReceiptOcrLimits,
    ReceiptOcrSource,
    TesseractTsvOcrEngine,
    extract_and_persist_receipt_ocr_evidence,
)
from finance_core.intake.receipt_ocr_proposal import (
    InvalidProposalCommandError,
    OcrExtractionNotFoundError,
    ProposalCallerOwnedTransactionError,
    ProposalDuplicateInitialError,
    ProposalIdempotencyConflictError,
    ProposalPersistenceConflictError,
    ProposalSourceBindingConflictError,
    ProposalStagingDatabaseRejectedError,
    ProposalUnexpectedPersistenceError,
    ReceiptOcrProposalError,
    ReceiptTotalProposalIngestionResult,
    UnusableOcrEvidenceError,
    ingest_receipt_ocr_evidence_as_total_expense_proposal,
)
from finance_core.intake.telegram_attachment_acquisition import (
    AcquisitionReplayConflictError,
    AcquisitionReplayIntegrityError,
    AttachmentEvidenceHandoffConflictError,
    CallerOwnedTransactionError,
    ContentSignatureMismatchError,
    DurableFileIntegrityConflictError,
    DurablePublicationError,
    InvalidAcquisitionConfigurationError,
    InvalidRemoteFilePathError,
    InvalidTelegramIdentityError,
    MalformedTelegramMetadataError,
    RawIntakeNotFoundError,
    StagingDatabaseRejectedError,
    TelegramAttachmentAcquisitionError,
    TelegramAttachmentAcquisitionLimits,
    TelegramAttachmentAcquisitionResult,
    TelegramAttachmentTransport,
    TelegramDeclaredFileTooLargeError,
    TelegramDownloadResponse,
    TelegramDownloadTimeoutError,
    TelegramFileMetadata,
    TelegramHttpResponseError,
    TelegramMetadataRequestError,
    TelegramRedirectError,
    TelegramStreamedFileTooLargeError,
    TelegramTruncatedDownloadError,
    TemporaryFileCleanupError,
    TemporaryFileError,
    UnexpectedAttachmentPersistenceError,
    UnsafeStorageRootError,
    UnsupportedFilenameExtensionError,
    UnsupportedMimeTypeError,
    acquire_and_persist_telegram_attachment,
)
from finance_core.intake.telegram_bot_api_transport import TelegramBotApiTransport

__all__ = [
    "persist_attachment_evidence",
    "get_attachment_evidence",
    "AttachmentEvidenceError",
    "AttachmentFileNotFoundError",
    "AttachmentFileUnreadableError",
    "AttachmentFileChangedDuringHashError",
    "AttachmentEvidenceConflictError",
    "AttachmentEvidencePersistenceError",
    "AttachmentRawIntakeConflictError",
    "InvalidAttachmentIdentityError",
    "AttachmentExpectedSizeMismatchError",
    "AttachmentExpectedHashMismatchError",
    "acquire_and_persist_telegram_attachment",
    "TelegramBotApiTransport",
    "TelegramAttachmentAcquisitionLimits",
    "TelegramAttachmentAcquisitionResult",
    "TelegramFileMetadata",
    "TelegramAttachmentTransport",
    "TelegramDownloadResponse",
    "TelegramAttachmentAcquisitionError",
    "InvalidAcquisitionConfigurationError",
    "InvalidTelegramIdentityError",
    "StagingDatabaseRejectedError",
    "CallerOwnedTransactionError",
    "RawIntakeNotFoundError",
    "UnsafeStorageRootError",
    "TelegramMetadataRequestError",
    "MalformedTelegramMetadataError",
    "InvalidRemoteFilePathError",
    "TelegramHttpResponseError",
    "TelegramRedirectError",
    "TelegramDownloadTimeoutError",
    "TelegramDeclaredFileTooLargeError",
    "TelegramStreamedFileTooLargeError",
    "TelegramTruncatedDownloadError",
    "UnsupportedMimeTypeError",
    "UnsupportedFilenameExtensionError",
    "ContentSignatureMismatchError",
    "TemporaryFileCleanupError",
    "TemporaryFileError",
    "DurablePublicationError",
    "DurableFileIntegrityConflictError",
    "AcquisitionReplayConflictError",
    "AcquisitionReplayIntegrityError",
    "AttachmentEvidenceHandoffConflictError",
    "UnexpectedAttachmentPersistenceError",
    "extract_and_persist_receipt_ocr_evidence",
    "TesseractTsvOcrEngine",
    "MacOSVisionOcrEngine",
    "MACOS_VISION_HELPER_NAME",
    "MACOS_VISION_HELPER_PROTOCOL_VERSION",
    "MACOS_VISION_MAX_LANGUAGE_COUNT",
    "MACOS_VISION_RECOGNITION_LEVEL",
    "MACOS_VISION_REQUEST_REVISION",
    "MACOS_VISION_USES_LANGUAGE_CORRECTION",
    "convert_vision_bounding_box",
    "convert_vision_observations",
    "scale_vision_confidence",
    "ReceiptOcrLimits",
    "ReceiptOcrExtractionStatus",
    "ReceiptOcrEngineIdentity",
    "ReceiptOcrSource",
    "ReceiptOcrBlock",
    "ReceiptOcrEngineResult",
    "ReceiptOcrEngine",
    "ReceiptOcrExtractionResult",
    "ReceiptOcrError",
    "InvalidOcrConfigurationError",
    "OcrStagingDatabaseRejectedError",
    "OcrCallerOwnedTransactionError",
    "OcrAttachmentNotFoundError",
    "OcrAttachmentIntegrityConflictError",
    "OcrUnsupportedPlatformError",
    "OcrEngineLaunchError",
    "OcrDeadlineExceededError",
    "OcrResourceLimitExceededError",
    "OcrProcessCleanupError",
    "MalformedOcrOutputError",
    "OcrIdempotencyConflictError",
    "OcrPersistenceConflictError",
    "OcrUnexpectedPersistenceError",
    "ingest_receipt_ocr_evidence_as_total_expense_proposal",
    "ReceiptTotalProposalIngestionResult",
    "ReceiptOcrProposalError",
    "InvalidProposalCommandError",
    "ProposalStagingDatabaseRejectedError",
    "ProposalCallerOwnedTransactionError",
    "OcrExtractionNotFoundError",
    "UnusableOcrEvidenceError",
    "ProposalSourceBindingConflictError",
    "ProposalIdempotencyConflictError",
    "ProposalDuplicateInitialError",
    "ProposalPersistenceConflictError",
    "ProposalUnexpectedPersistenceError",
]
