"""Stable error taxonomy for the OpenClaw staging bridge CLI.

Every refusal fails closed with a stable machine-readable code, a bounded
human message, a retryability flag, and the §5.4 exit code.  Codes are part
of the v1 CLI contract and must not be renamed silently.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Mapping

# ---------------------------------------------------------------------------
# Exit codes (design §5.4)
# ---------------------------------------------------------------------------

EXIT_OK = 0
EXIT_USAGE = 2
EXIT_MALFORMED_ENVELOPE = 3
EXIT_UNKNOWN_COMMAND = 4
EXIT_VALIDATION_REFUSED = 5
EXIT_AUTHORITY_REFUSED = 6
EXIT_DEADLINE_EXCEEDED = 7
EXIT_INTERNAL = 8

# ---------------------------------------------------------------------------
# Stable error codes
# ---------------------------------------------------------------------------

MALFORMED_ENVELOPE = "MALFORMED_ENVELOPE"
OVERSIZED_ENVELOPE = "OVERSIZED_ENVELOPE"
ENVELOPE_TOO_DEEP = "ENVELOPE_TOO_DEEP"
UNKNOWN_COMMAND = "UNKNOWN_COMMAND"
MISSING_IDEMPOTENCY_KEY = "MISSING_IDEMPOTENCY_KEY"
ARGUMENTS_REFUSED = "ARGUMENTS_REFUSED"
WORKSPACE_REFUSED = "WORKSPACE_REFUSED"
WORKSPACE_MISSING = "WORKSPACE_MISSING"
STAGING_REFUSED = "STAGING_REFUSED"
INTAKE_NOT_FOUND = "INTAKE_NOT_FOUND"
PROPOSAL_NOT_FOUND = "PROPOSAL_NOT_FOUND"
ATTACHMENT_EVIDENCE_NOT_FOUND = "ATTACHMENT_EVIDENCE_NOT_FOUND"
IDEMPOTENCY_CONFLICT = "IDEMPOTENCY_CONFLICT"
HANDOFF_REFUSED = "HANDOFF_REFUSED"
HANDOFF_NOT_FOUND = "HANDOFF_NOT_FOUND"
UNSUPPORTED_UPDATE_TYPE = "UNSUPPORTED_UPDATE_TYPE"
TELEGRAM_SOURCE_REFUSED = "TELEGRAM_SOURCE_REFUSED"
OCR_ENGINE_UNAVAILABLE = "OCR_ENGINE_UNAVAILABLE"
OCR_EXTRACTION_FAILED = "OCR_EXTRACTION_FAILED"
PROPOSAL_UNAVAILABLE = "PROPOSAL_UNAVAILABLE"
CALLBACK_KEY_MISSING = "CALLBACK_KEY_MISSING"
CALLBACK_KEY_UNSAFE = "CALLBACK_KEY_UNSAFE"
CALLBACK_EXPIRED = "CALLBACK_EXPIRED"
CALLBACK_TOKEN_INVALID = "CALLBACK_TOKEN_INVALID"
CALLBACK_WRONG_ACTION = "CALLBACK_WRONG_ACTION"
HUMAN_ACTION_REFERENCE_INVALID = "HUMAN_ACTION_REFERENCE_INVALID"
HUMAN_ACTION_REFERENCE_REPLAYED = "HUMAN_ACTION_REFERENCE_REPLAYED"
STALE_VERSION = "STALE_VERSION"
STALE_CONTENT_HASH = "STALE_CONTENT_HASH"
PROPOSAL_TERMINAL_STATE = "PROPOSAL_TERMINAL_STATE"
LIFECYCLE_CONFLICT = "LIFECYCLE_CONFLICT"
UNSUPPORTED_EDIT = "UNSUPPORTED_EDIT"
NO_MATERIAL_CHANGE = "NO_MATERIAL_CHANGE"
FINALIZATION_REFUSED = "FINALIZATION_REFUSED"
FINALIZATION_LOCKED = "FINALIZATION_LOCKED"
ACTOR_MISMATCH = "ACTOR_MISMATCH"
SNAPSHOT_AUTHORIZATION_REQUIRED = "SNAPSHOT_AUTHORIZATION_REQUIRED"
STALE_SNAPSHOT = "STALE_SNAPSHOT"
DEADLINE_EXCEEDED = "DEADLINE_EXCEEDED"
INTERNAL_ERROR = "INTERNAL_ERROR"
RESPONSE_TOO_LARGE = "RESPONSE_TOO_LARGE"
AI_FALLBACK_NOT_FOUND = "AI_FALLBACK_NOT_FOUND"
AI_FALLBACK_NOT_ELIGIBLE = "AI_FALLBACK_NOT_ELIGIBLE"
AI_FALLBACK_CONFLICT = "AI_FALLBACK_CONFLICT"
AI_FALLBACK_ARGUMENTS_REFUSED = "AI_FALLBACK_ARGUMENTS_REFUSED"
AI_FALLBACK_POLICY_REFUSED = "AI_FALLBACK_POLICY_REFUSED"
AI_FALLBACK_VALIDATION_REFUSED = "AI_FALLBACK_VALIDATION_REFUSED"
AI_FALLBACK_INTERNAL = "AI_FALLBACK_INTERNAL"
AI_MODEL_COMPATIBILITY_ARGUMENTS_REFUSED = "AI_MODEL_COMPATIBILITY_ARGUMENTS_REFUSED"
AI_MODEL_COMPATIBILITY_POLICY_REFUSED = "AI_MODEL_COMPATIBILITY_POLICY_REFUSED"
AI_MODEL_COMPATIBILITY_FK_REFUSED = "AI_MODEL_COMPATIBILITY_FK_REFUSED"
AI_MODEL_COMPATIBILITY_CONFLICT = "AI_MODEL_COMPATIBILITY_CONFLICT"
AI_MODEL_COMPATIBILITY_INTERNAL = "AI_MODEL_COMPATIBILITY_INTERNAL"
AI_MODEL_CONFIG_REFUSED = "AI_MODEL_CONFIG_REFUSED"
AI_MODEL_CONFIG_NOT_ACCEPTED = "AI_MODEL_CONFIG_NOT_ACCEPTED"
AI_MODEL_EVAL_REFUSED = "AI_MODEL_EVAL_REFUSED"

_RETRYABLE_CODES = frozenset(
    {
        DEADLINE_EXCEEDED,
        FINALIZATION_LOCKED,
        INTERNAL_ERROR,
        STAGING_REFUSED,
        WORKSPACE_MISSING,
    }
)
# OCR_ENGINE_UNAVAILABLE is intentionally excluded: it is a fail-closed
# refusal with no retryable remedy until a trusted engine resolver is wired.


@dataclass(frozen=True)
class BridgeError(Exception):
    """A fail-closed bridge refusal with a stable code and exit code.

    ``details`` is an optional bounded machine-readable projection of
    refusal context (identity strings, counts, reason discriminators).
    It never carries amounts, image bytes, key material, or database
    contents.  ``SNAPSHOT_AUTHORIZATION_REQUIRED`` uses it for the bounded
    snapshot review material (S4/D2B).
    """

    code: str
    message: str
    exit_code: int
    retryable: bool = False
    details: Mapping[str, str | int] | None = None

    def __str__(self) -> str:
        return f"{self.code}: {self.message}"


def bridge_error(
    code: str,
    message: str,
    exit_code: int,
    *,
    retryable: bool | None = None,
    details: Mapping[str, str | int] | None = None,
) -> BridgeError:
    resolved_retryable = retryable if retryable is not None else code in _RETRYABLE_CODES
    return BridgeError(
        code=code,
        message=message,
        exit_code=exit_code,
        retryable=resolved_retryable,
        details=None if details is None else dict(details),
    )


__all__ = [
    "ACTOR_MISMATCH",
    "AI_FALLBACK_ARGUMENTS_REFUSED",
    "AI_FALLBACK_CONFLICT",
    "AI_FALLBACK_INTERNAL",
    "AI_FALLBACK_NOT_ELIGIBLE",
    "AI_FALLBACK_NOT_FOUND",
    "AI_FALLBACK_POLICY_REFUSED",
    "AI_FALLBACK_VALIDATION_REFUSED",
    "AI_MODEL_COMPATIBILITY_ARGUMENTS_REFUSED",
    "AI_MODEL_COMPATIBILITY_POLICY_REFUSED",
    "AI_MODEL_COMPATIBILITY_FK_REFUSED",
    "AI_MODEL_COMPATIBILITY_CONFLICT",
    "AI_MODEL_COMPATIBILITY_INTERNAL",
    "AI_MODEL_CONFIG_REFUSED",
    "AI_MODEL_CONFIG_NOT_ACCEPTED",
    "AI_MODEL_EVAL_REFUSED",
    "ARGUMENTS_REFUSED",
    "ATTACHMENT_EVIDENCE_NOT_FOUND",
    "CALLBACK_EXPIRED",
    "CALLBACK_KEY_MISSING",
    "CALLBACK_KEY_UNSAFE",
    "CALLBACK_TOKEN_INVALID",
    "CALLBACK_WRONG_ACTION",
    "DEADLINE_EXCEEDED",
    "ENVELOPE_TOO_DEEP",
    "EXIT_AUTHORITY_REFUSED",
    "EXIT_DEADLINE_EXCEEDED",
    "EXIT_INTERNAL",
    "EXIT_MALFORMED_ENVELOPE",
    "EXIT_OK",
    "EXIT_UNKNOWN_COMMAND",
    "EXIT_USAGE",
    "EXIT_VALIDATION_REFUSED",
    "FINALIZATION_LOCKED",
    "FINALIZATION_REFUSED",
    "BridgeError",
    "HANDOFF_NOT_FOUND",
    "HANDOFF_REFUSED",
    "HUMAN_ACTION_REFERENCE_INVALID",
    "HUMAN_ACTION_REFERENCE_REPLAYED",
    "IDEMPOTENCY_CONFLICT",
    "INTERNAL_ERROR",
    "INTAKE_NOT_FOUND",
    "LIFECYCLE_CONFLICT",
    "MALFORMED_ENVELOPE",
    "MISSING_IDEMPOTENCY_KEY",
    "NO_MATERIAL_CHANGE",
    "OCR_ENGINE_UNAVAILABLE",
    "OCR_EXTRACTION_FAILED",
    "OVERSIZED_ENVELOPE",
    "PROPOSAL_NOT_FOUND",
    "PROPOSAL_TERMINAL_STATE",
    "PROPOSAL_UNAVAILABLE",
    "RESPONSE_TOO_LARGE",
    "SNAPSHOT_AUTHORIZATION_REQUIRED",
    "STAGING_REFUSED",
    "STALE_CONTENT_HASH",
    "STALE_SNAPSHOT",
    "STALE_VERSION",
    "TELEGRAM_SOURCE_REFUSED",
    "UNKNOWN_COMMAND",
    "UNSUPPORTED_EDIT",
    "UNSUPPORTED_UPDATE_TYPE",
    "WORKSPACE_MISSING",
    "WORKSPACE_REFUSED",
    "bridge_error",
]
